$(document).ready(function(){
	$("#post_button1").click(function(){
		$("#post_ans1").toggle();
	});
	$("#post_button2").click(function(){
		$("#post_ans2").toggle();
	});
	$("#post_button3").click(function(){
		$("#post_ans3").toggle();
	});
	$("#post_button4").click(function(){
		$("#post_ans4").toggle();
	});
	$("#post_button5").click(function(){
		$("#post_ans5").toggle();
	});
	$("#post_button6").click(function(){
		$("#post_ans6").toggle();
	});
	$("#post_button7").click(function(){
		$("#post_ans7").toggle();
	});
	$("#post_button8").click(function(){
		$("#post_ans8").toggle();
	});
	$("#post_button9").click(function(){
		$("#post_ans9").toggle();
	});
	$("#post_button10").click(function(){
		$("#post_ans10").toggle();
	});
	$("#post_button11").click(function(){
		$("#post_ans11").toggle();
	});
	$("#post_button12").click(function(){
		$("#post_ans12").toggle();
	});
	$("#post_button13").click(function(){
		$("#post_ans13").toggle();
	});
	$("#post_button14").click(function(){
		$("#post_ans14").toggle();
	});
	$("#post_button15").click(function(){
		$("#post_ans15").toggle();
	});
	$("#post_button16").click(function(){
		$("#post_ans16").toggle();
	});
	$("#post_button17").click(function(){
		$("#post_ans17").toggle();
	});
	$("#post_button18").click(function(){
		$("#post_ans18").toggle();
	});
	$("#post_button19").click(function(){
		$("#post_ans19").toggle();
	});
	$("#post_button20").click(function(){
		$("#post_ans20").toggle();
	});
	
});